FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/media-worker ./cmd/media-worker

FROM alpine:3.22.1
RUN apk add --no-cache ca-certificates ffmpeg clamav && freshclam
COPY --from=build /out/media-worker /media-worker
USER 65532:65532
ENTRYPOINT ["/media-worker"]
