'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import type { MediaItem, MediaPage } from '@/lib/api/media';

type Batch={id:string;name:string;status:'draft'|'submitted'|'in_review'|'approved'|'rejected';itemCount:number;submittedAt?:string;reviewFeedback?:string;reviewedAt?:string;createdAt:string;updatedAt:string};
type BatchPage={items:Batch[];total:number};

export function BatchManager(){
  const[batches,setBatches]=useState<Batch[]>([]);const[assets,setAssets]=useState<MediaItem[]>([]);const[selection,setSelection]=useState<Record<string,string>>({});const[message,setMessage]=useState('Loading batches…');
  const load=useCallback(async()=>{try{const[batchResponse,mediaResponse]=await Promise.all([fetch('/api/batches',{cache:'no-store'}),fetch('/api/media',{cache:'no-store'})]);if(!batchResponse.ok||!mediaResponse.ok)throw new Error();const batchPage=await batchResponse.json() as BatchPage;const mediaPage=await mediaResponse.json() as MediaPage;setBatches(batchPage.items);setAssets(mediaPage.items.filter(asset=>asset.status==='ready'));setMessage('');}catch{setMessage('Unable to load batches.');}},[]);
  useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const name=String(new FormData(form).get('name')??'');setMessage('Creating batch…');const response=await fetch('/api/batches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})});if(response.ok){form.reset();await load();}else setMessage('Unable to create batch.');}
  async function add(batchID:string){const assetId=selection[batchID];if(!assetId)return;setMessage('Adding media…');const response=await fetch(`/api/batches/${encodeURIComponent(batchID)}/items`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({assetId})});if(response.ok)await load();else setMessage('That media cannot be added to this batch.');}
  async function submit(batchID:string){setMessage('Submitting batch…');const response=await fetch(`/api/batches/${encodeURIComponent(batchID)}/submit`,{method:'POST'});if(response.ok)await load();else setMessage('Every item needs a title, classification, and keyword before submission.');}
  return <section className="batch-manager" aria-labelledby="batches-heading"><form onSubmit={create}><label htmlFor="batch-name">New batch</label><div><input id="batch-name" name="name" maxLength={120} required placeholder="e.g. Lagos street life"/><button className="primary small" type="submit">Create batch</button></div></form><p role="status" aria-live="polite">{message}</p><h2 id="batches-heading">Your batches</h2>{!message&&batches.length===0&&<p>Create a batch to organise ready media for review.</p>}<div className="batch-list">{batches.map(batch=><article key={batch.id}><div><h3>{batch.name}</h3><span className={`media-status media-status--${batch.status}`}>{batch.status.replace('_',' ')}</span></div><p>{batch.itemCount} item{batch.itemCount===1?'':'s'}</p>{batch.reviewFeedback&&<p className="review-feedback"><b>Reviewer feedback:</b> {batch.reviewFeedback}</p>}{batch.status==='draft'&&<><div className="batch-add"><select aria-label={`Media for ${batch.name}`} value={selection[batch.id]??''} onChange={event=>setSelection(current=>({...current,[batch.id]:event.target.value}))}><option value="">Choose ready media</option>{assets.map(asset=><option value={asset.id} key={asset.id}>{asset.title??asset.filename}</option>)}</select><button type="button" onClick={()=>void add(batch.id)}>Add</button></div><button className="primary small" type="button" disabled={batch.itemCount<1} onClick={()=>void submit(batch.id)}>Submit for review</button></>}</article>)}</div></section>;
}
