'use client';
import { FormEvent, useEffect, useState } from 'react';
type Collection={id:string;name:string;itemCount:number;mediaIds:string[]};
export function SaveToCollection({assetId}:{assetId:string}){
  const [collections,setCollections]=useState<Collection[]>([]);const [selected,setSelected]=useState('');const [favourite,setFavourite]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{void Promise.all([fetch('/api/collections'),fetch('/api/favourites')]).then(async([a,b])=>{if(a.ok){const body=await a.json();setCollections(body.items);setSelected(body.items[0]?.id??'');}if(b.ok){const body=await b.json();setFavourite(body.mediaIds.includes(assetId));}});},[assetId]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const name=String(new FormData(form).get('name')??'');const response=await fetch('/api/collections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})});if(response.ok){const item=await response.json();setCollections(current=>[item,...current]);setSelected(item.id);form.reset();setMessage('Collection created.');}else setMessage('Unable to create collection.');}
  async function save(){if(!selected){setMessage('Create a collection first.');return;}const response=await fetch(`/api/collections/${encodeURIComponent(selected)}/items/${encodeURIComponent(assetId)}`,{method:'PUT'});setMessage(response.ok?'Saved to collection.':'Unable to save this item.');}
  async function toggleFavourite(){const next=!favourite;const response=await fetch(`/api/favourites/${encodeURIComponent(assetId)}`,{method:next?'PUT':'DELETE'});if(response.ok){setFavourite(next);setMessage(next?'Added to favourites.':'Removed from favourites.');}else setMessage('Sign in with a buyer account to save favourites.');}
  return <section aria-label="Save media"><button className="primary" type="button" onClick={toggleFavourite}>{favourite?'Remove favourite':'Add to favourites'}</button><div><select aria-label="Collection" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose collection</option>{collections.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" onClick={save}>Save to collection</button></div><form onSubmit={create}><input name="name" aria-label="New collection name" placeholder="New collection" maxLength={120} required/><button type="submit">Create</button></form>{message&&<p role="status">{message}</p>}</section>;
}
