'use client';
import { ImageIcon } from 'lucide-react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { FormEvent, Suspense, useState } from 'react';
import { defaultRoute, type AccountRole } from '@/lib/auth/session';

const noticeVersion='2026-09-09';
function LoginContent(){
  const [register,setRegister]=useState(true);const [role,setRole]=useState<AccountRole>('contributor');const [status,setStatus]=useState<{kind:'idle'|'busy'|'error'|'success';message?:string}>({kind:'idle'});const router=useRouter();const query=useSearchParams();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus({kind:'busy'});const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const requestBody=register?{...payload,role,noticeVersion,privacyNoticeAcknowledged:payload.privacyNoticeAcknowledged==='on'}:{...payload,role};try{const response=await fetch(register?'/api/auth/register':'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(requestBody)});const body=await response.json();if(!response.ok)throw new Error(body.detail??'Unable to continue');if(register){setStatus({kind:'success',message:body.message});return;}const returnTo=query.get('returnTo');const safeReturn=returnTo?.startsWith('/')&&!returnTo.startsWith('//')?returnTo:defaultRoute(body.user.role);router.replace(safeReturn);router.refresh();}catch(error){setStatus({kind:'error',message:error instanceof Error?error.message:'Unable to continue'});}}
  return <main className="auth"><div className="authImage"><div className="logo light"><span><ImageIcon size={21}/></span> tamoimages</div><div><h1>Start making money from what you love doing</h1><p>Join a marketplace made for African photographers, videographers and artists.</p></div></div><form className="authForm" onSubmit={submit} aria-busy={status.kind==='busy'}><div className="switch" aria-label="Account type"><button className={role==='contributor'?'active':''} type="button" onClick={()=>setRole('contributor')}>Contributor</button><button className={role==='buyer'?'active':''} type="button" onClick={()=>setRole('buyer')}>Buyer</button></div><p>{register?'Have an account already?':'New to Tamo Images?'} <button type="button" onClick={()=>{setRegister(!register);setStatus({kind:'idle'});}}>{register?'Log in':'Sign up'}</button></p><h1>{register?'New to Tamo Images?':'Welcome back'}</h1><input name="email" type="email" autoComplete="email" aria-label="Email address" placeholder="Email" required/>{register&&<div className="row"><input name="firstName" autoComplete="given-name" aria-label="First name" placeholder="First name" required/><input name="lastName" autoComplete="family-name" aria-label="Last name" placeholder="Last name" required/></div>}<input name="password" type="password" autoComplete={register?'new-password':'current-password'} aria-label="Password" placeholder="Password" minLength={register?12:1} maxLength={128} required/>{register&&<label className="ui-choice"><input name="privacyNoticeAcknowledged" type="checkbox" required/><span>I have read the <Link href="/privacy" target="_blank">privacy notice</Link> (version {noticeVersion}).</span></label>}{status.message&&<p className={`form-status form-status--${status.kind}`} role={status.kind==='error'?'alert':'status'}>{status.message}</p>}<button className="primary" disabled={status.kind==='busy'} type="submit">{status.kind==='busy'?'Please wait…':register?'Register':'Log in'}</button></form></main>;
}
export default function Login(){return <Suspense fallback={<main className="authStandalone" aria-busy="true">Loading…</main>}><LoginContent/></Suspense>}
